export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LOAD_DEWDROPS_SUCCESS = 'LOAD_DEWDROPS_SUCCESS';
export const CREATE_DEWDROP_SUCCESS = 'CREATE_DEWDROP_SUCCESS';

export const LOAD_CURRENT_DEWDROP_SUCCESS = 'LOAD_CURRENT_DEWDROP_SUCCESS';

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
